### PR TITLE
Upgrade to hie-bios 0.3

### PR DESCRIPTION
**Pull request by cocreature**
This does not yet take advantage of any new features but we should at
least be able to benefit from bugfixes.

### CODE REVIEW

**Comment by mpickering** [comment]
Note that anything configured with the multi-cradle will also not work with `ghcide` because you pass the empty path when trying to determine which component to use.

**Comment by cocreature** [comment]
Right but that was already the case before. Multicomponent cradles definitely don’t work at the moment.

**Comment by symbiont-eric-torreborre** [comment]
> Right but that was already the case before. Multicomponent cradles definitely don’t work at the moment.

This deserves a bigger note in the release notes, I was wondering what I was doing wrong :-). Is it still possible to load only the modules from one of the components though?

**Comment by cocreature** [comment]
If you set your `hie.yaml` to a cabal cradle that loads one component it should work fine (see  https://github.com/mpickering/hie-bios#explicit-configuration). You can also manually construct a direct cradle that merges the components and sets things like default extensions and include paths manually (getting packages can be a bit tricky but the ghc environment files that cabal writes by default should be picked up).

**Comment by domenkozar** [comment]
I think previously by default stack would load lib and exe components, whereas with the upgrade I can only specify one component (since multi-cradle isn't supported yet). Is that correct observation?

**Comment by cocreature** [comment]
As far as I know `cradle: { stack: {}}` should be equivalent to the stack cradle on older `hie-bios` versions.

**Comment by domenkozar** [comment]
That's what I thought, but hie-bios fails since stack asks to pick the component between lib, exes and tests.

**Comment by cocreature** [comment]
Not sure what is going on then. Maybe worth opening an issue in `hie-bios` for that.

**Comment by fendor** [comment]
We no longer pass in filepaths to `stack repl` but components which likely explains this behaviour. If you are not using a component, just `stack repl` is used, which asks to pick the component if there are multiple exes, for example.

**Comment by cocreature** [comment]
We never did pass a file path in `ghcide`, we just set that to an empty string so I’m still struggling to see what changed here. Could it be that this never worked if you have more than one main module?

**Pull request merged**
