### PR TITLE
Add goto/hover tests for type constructors from other package

### PR DESCRIPTION
**Pull request by jacg**
Add *go to defirition* and *hover* tests for type constructors which are defined in a different package. This adds a new row, *external type constructor*, to the table from #139:

| | find definition | hover |
|-------------|-----------|---------|
| field in record definition | :heavy_check_mark:  | :heavy_check_mark: |
| field in record construction | :x:  | :x: |
| field name as accessor | :heavy_check_mark: | :heavy_check_mark: |
| top level name | :heavy_check_mark: | :heavy_check_mark: |
| record data constructor | :x: | :x: |
| plain data constructor | :heavy_check_mark: | :heavy_check_mark:  |
| type constructor | :heavy_check_mark: | :x: |
| external type constructor | :heavy_minus_sign: | :x: |
| plain parameter | :heavy_check_mark: | :heavy_check_mark: |
| pattern match name | :heavy_check_mark: | :heavy_check_mark: |
| top level operator | :heavy_check_mark: | :heavy_check_mark: |
| parameter operator | :heavy_check_mark:  | :heavy_check_mark:  |
| name in backticks | :heavy_check_mark: | :heavy_check_mark: |

*go to definition* (for type constructors from other packages) probably can't be made to work at all, although one might argue that you should be taken to the line that imports the type.

*hover* should probably display the module from which the name is imported.

### CODE REVIEW

**Comment by jacg** [comment]
Maintaining the source code on which these tests operate, in `Text` within the test source code, is getting rather unwieldy. So I tried to move it out to a separate source file, and use `openDoc` instead of `openDoc'` but I had no success. Even though the file is read in correctly, no definitions or hovers are ever found at all. Maybe there's something I'm not understanding about the effects of the `--cwd` option to `ghcide`. Any thoughts?

I'd like to have a go at turning some of these :x:s into  :heavy_check_mark:s but I get lost among the thousands of type constructors in the GHC API, with which I am not at all familiar. Any suggestions?

**Comment by aherrmann-da** [comment]
> Maintaining the source code on which these tests operate, in `Text` within the test source code, is getting rather unwieldy. So I tried to move it out to a separate source file, and use `openDoc` instead of `openDoc'` but I had no success. Even though the file is read in correctly, no definitions or hovers are ever found at all. Maybe there's something I'm not understanding about the effects of the `--cwd` option to `ghcide`. Any thoughts?

Do you have that trial available in a branch somewhere?

**Comment by cocreature** [comment]
> Conceivably, it could do something like IntelliJ and download sources. But, that's not available right now.

We already have most of the infrastructure for this in place assuming there are `.hie` files available for the dependencies. Locating the sources and hie files is parametrized so we could fairly easily swap this out. Cabal usually has the sources somewhere in `~/.cabal` so it would be feasible to point there.

**Comment by jacg** [comment]
@aherrmann-da 

> Do you have that trial available in a branch somewhere?

[here](https://github.com/jacg/ghcide/tree/external-test-source)

**Comment by aherrmann-da** [comment]
@jacg I took a look at the `openDoc` issue. The confusing bit is that the LSP session runs in a temporary directory, but the test runner still runs in the repository root. One way to deal with this is to refer to the source file by absolute path, like so:
``` diff
--- a/test/exe/Main.hs
+++ b/test/exe/Main.hs
@@ -692,7 +692,8 @@ findDefinitionTests :: TestTree
 findDefinitionTests = let

   tst (get, check) pos targetRange title = testSession title $ do
-    doc <- openDoc' "Testing.hs" "haskell" source
+    sourceFile <- liftIO (makeAbsolute "test/data/GotoHover.hs")
+    doc <- openDoc sourceFile "haskell"
     found <- get doc pos
     check found targetRange
```
In that case you'll want to make sure that the test case doesn't modify the source file. Copying the file into the temporary session directory might be a safer option.

You should also add the source file to the `extra-source-files` section in the Cabal file, to make sure that it's included in source distributions.

**Comment by jacg** [comment]
@aherrmann-da Thanks. This approach was still giving me problems, and in the end it seemed simpler and safer to copy the file into the temporary session directory with a combination of `readFile` and `openDoc'`, and I have submitted this approach in #175.

**Pull request merged**
