### PR TITLE
Enhancements to Haddock -> Markdown conversion

### LINKED ISSUE #341: Some parts of the doc info (on hover) are incorrectly wrapped inside code tags
The overall feature looks neat, but some parts of the `:doc` are incorrectly wrapped in `<code></code>`

image

As @serras [points out](https://github.com/digital-asset/ghcide/pull/317#issuecomment-577678395), the origin of this may be at the transform of Haddock into Markdown.

---

Should this be reported in https://github.com/haskell/haddock instead, please let me know.

### PR DESCRIPTION
**Pull request by serras**
Fixes #341

### CODE REVIEW

**Comment by ndmitchell** [comment]
Any chance of some tests? I could imagine future changes breaking some of the more subtle bits.

**Comment by serras** [comment]
I can try, but I've already had the problem that the documentation from packages changes from version to version. I'm planning to have a look at #7 and #270, and then we can write tests which reference files in the project itself.

**Comment by ndmitchell** [comment]
I was thinking just a pure function, so take the Show of the DocH for unsafePerformIO as it stands today, paste it in as a test, and paste the current output as a string, and confirm that the conversion takes one to the other.

**Comment by serras** [comment]
That makes sense. I'll write some of them during the weekend.

**Comment by serras** [comment]
@ndmitchell the tests are in. Let me tell you what you think. Right now I've chosen two of the "hardest" ones: `Num` and `unsafePerformIO`, since they involve lists and mixed code.

**Comment by ndmitchell** [comment]
Tests look great! Thanks for doing that.

**Pull request merged**
