### PR TITLE
Strip path information from diagnostic messages (#158)

### PR DESCRIPTION
**Pull request by tek**
As discussed in #158. Don't know if the test is up to standard, please advise.

### CODE REVIEW

**Comment by tek** [comment]
looks like the test "redundant operator" failed, doesn't look related to this PR

**Comment by pepeiborra** [comment]
> looks like the test "redundant operator" failed, doesn't look related to this PR

This PR changes the parsing of error messages into diagnostics, which are then analysed by the code actions logic to suggest fixes. So it is very much related.

**Comment by tek** [comment]
ok, then I'll have another look!

**Comment by tek** [comment]
The offending location had an `#if` on the ghc version to define the expected message, and with the changes the message for 8.4 became the same as for 8.6. I would speculate that using `ErrUtils.formatErrDoc` just coincides the two paths and that simply removing the `#if` is a proper fix, but I know too little about the project. What's your assessment of this, @pepeiborra ?

**Comment by ndmitchell** [comment]
@tek - if that fixes the test, it's very likely the right solution - sounds totally plausible.

**Comment by tek** [comment]
wonderful!

**Review by cocreature — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
