### PR TITLE
Use tasty-rerun to allow rerunning failed tests only

### PR DESCRIPTION
**Pull request by alanz**
Use by

  stack --stack-yaml=stack84.yaml test --test-arguments "--rerun"

### CODE REVIEW

**Comment by ocharles** [comment]
Ha, cool to see some of my early creations have users! :smile:

**Comment by alanz** [comment]
I am used to this basic functionality in hspec.

I would *love* to have the equivalent of the hspec `--match` capability to just run arbitrary tests.

And this is the fundamental reason haskell-language-server decided to stick with hspec for tests.

But now I am diving into ghcide myself, need to improve the experience a bit.

**Comment by cocreature** [comment]
> I would _love_ to have the equivalent of the hspec `--match` capability to just run arbitrary tests.

Are you looking for Tasty’s `-p` flag?

**Comment by alanz** [comment]
> Are you looking for Tasty’s -p flag?

Sounds like it. I did a search but did not find anything, obviously not looking that well.

**Comment by cocreature** [comment]
Tasty’s readme has pretty decent documentation for it https://github.com/feuerbach/tasty/#patterns

**Comment by jneira** [comment]
i personally like hspec `--match` and `--skip` matching rules over tasty `--pattern` (but i guess it is matter of habit)

**Pull request merged**
