### PR TITLE
Prepare for archiving the Github project

### PR DESCRIPTION
**Pull request by pepeiborra**
Last PR before archiving

### CODE REVIEW

**Review by jneira — APPROVED** [review]

**Comment by alanz** [comment]
What about the issues? They will also become read only. Should they have matching ones on HLS first?

**Comment by jneira** [comment]
@alanz yeah, maybe we should link from ghcide to hls, close some of them without translating, etc

**Comment by jneira** [comment]
After further debate in irc the plan would be handle all issues one by one:
* transferring the missing ones in hls
* "merge" with the correlated hls issue (linking or copying relevant comments)
* closing with a comment the no reproducible or with missing feedback from the author

Issues will be closed and the repo should be keep active meanwhile

**Comment by pepeiborra** [comment]
I think we need to transfer all the closed issues too, to prevent lost knowledge. The "transfer issue" link rewrites # references in comments to point to the old repo, and installs a redirection from the old # to the new # so it should all work fine.

**Pull request merged**
